"""Database package public API."""

from kis_portfolio.db.connection import close_connection, get_connection
from kis_portfolio.db.repository import (
    count_market_calendar_rows,
    get_asset_overview_snapshots,
    get_classification_override,
    get_classification_override_map,
    get_domestic_orders,
    get_exchange_rate_history,
    get_instrument_master,
    get_instrument_master_map,
    get_latest_order_history_snapshot,
    get_latest_overseas_order_history_snapshot,
    get_latest_overseas_transaction_history_snapshot,
    get_market_calendar_entry,
    get_overseas_orders,
    get_overseas_transactions,
    get_portfolio_snapshots,
    get_price_history,
    has_price_history,
    insert_asset_holding_snapshots,
    insert_asset_overview_snapshot,
    insert_order_history,
    insert_overseas_order_history,
    insert_overseas_asset_snapshot,
    insert_overseas_settlement_balance_snapshot,
    insert_overseas_transaction_history,
    insert_portfolio_snapshot,
    insert_trade_profit,
    upsert_domestic_orders,
    upsert_overseas_orders,
    upsert_overseas_transactions,
    upsert_market_calendar_rows,
    upsert_instrument_master,
    upsert_exchange_rate_history,
    upsert_price_history,
)
from kis_portfolio.db.schema import init_schema

__all__ = [
    "close_connection",
    "count_market_calendar_rows",
    "get_asset_overview_snapshots",
    "get_classification_override",
    "get_classification_override_map",
    "get_domestic_orders",
    "get_connection",
    "get_exchange_rate_history",
    "get_instrument_master",
    "get_instrument_master_map",
    "get_latest_order_history_snapshot",
    "get_latest_overseas_order_history_snapshot",
    "get_latest_overseas_transaction_history_snapshot",
    "get_market_calendar_entry",
    "get_overseas_orders",
    "get_overseas_transactions",
    "get_portfolio_snapshots",
    "get_price_history",
    "has_price_history",
    "init_schema",
    "insert_asset_holding_snapshots",
    "insert_asset_overview_snapshot",
    "insert_order_history",
    "insert_overseas_order_history",
    "insert_overseas_asset_snapshot",
    "insert_overseas_settlement_balance_snapshot",
    "insert_overseas_transaction_history",
    "insert_portfolio_snapshot",
    "insert_trade_profit",
    "upsert_domestic_orders",
    "upsert_overseas_orders",
    "upsert_overseas_transactions",
    "upsert_market_calendar_rows",
    "upsert_instrument_master",
    "upsert_exchange_rate_history",
    "upsert_price_history",
]
